//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bah! Shoulda known. .
        /// </summary>
        internal static string AlreadyKnown {
            get {
                return ResourceManager.GetString("AlreadyKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! Let&apos;s begin playing!.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your word contain the letter .
        /// </summary>
        internal static string CompGuess {
            get {
                return ResourceManager.GetString("CompGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve won!.
        /// </summary>
        internal static string CompWin {
            get {
                return ResourceManager.GetString("CompWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the word you were thinking.
        ///Enter : .
        /// </summary>
        internal static string EnterActual {
            get {
                return ResourceManager.GetString("EnterActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid file path for your word bank.
        ///Enter : .
        /// </summary>
        internal static string EnterFilePath {
            get {
                return ResourceManager.GetString("EnterFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please enter Y or N
        ///Enter : .
        /// </summary>
        internal static string EnterYN {
            get {
                return ResourceManager.GetString("EnterYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Oh no! I&apos;ll try again..
        /// </summary>
        internal static string FailedGuess {
            get {
                return ResourceManager.GetString("FailedGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the length of your word (Must be 25 characters or less)
        ///Enter : .
        /// </summary>
        internal static string GetUserLength {
            get {
                return ResourceManager.GetString("GetUserLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok! Goodbye!.
        /// </summary>
        internal static string GoodBye {
            get {
                return ResourceManager.GetString("GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I know the word. Is it .
        /// </summary>
        internal static string GuessWord {
            get {
                return ResourceManager.GetString("GuessWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darn..
        /// </summary>
        internal static string GuessWordWrong {
            get {
                return ResourceManager.GetString("GuessWordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid entry! Please input a valid entry.
        ///Enter : .
        /// </summary>
        internal static string InvalidEntry {
            get {
                return ResourceManager.GetString("InvalidEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current filepath to your word bank is invalid..
        /// </summary>
        internal static string InvalidFilePath {
            get {
                return ResourceManager.GetString("InvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve lost!.
        /// </summary>
        internal static string LostGame {
            get {
                return ResourceManager.GetString("LostGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, maybe I&apos;ll get it next time..
        /// </summary>
        internal static string NewWord {
            get {
                return ResourceManager.GetString("NewWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there another occurence of the letter .
        /// </summary>
        internal static string NextOccurence {
            get {
                return ResourceManager.GetString("NextOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Want to play again?.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Please read and follow the rules while playing,
        ///1. Don&apos;t cheat, it&apos;s just no fun.
        ///2. Your word must be a single word, no spaces, hyphens, or punctuation.
        ///.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |
        ///    |
        ///    |
        ///    |
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan0 {
            get {
                return ResourceManager.GetString("StickMan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |
        ///    |
        ///    |
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan1 {
            get {
                return ResourceManager.GetString("StickMan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |     |
        ///    |     |
        ///    |
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan2 {
            get {
                return ResourceManager.GetString("StickMan2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |    /|
        ///    |     |
        ///    |
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan3 {
            get {
                return ResourceManager.GetString("StickMan3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |    /|\
        ///    |     |
        ///    |
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan4 {
            get {
                return ResourceManager.GetString("StickMan4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |    /|\
        ///    |     |
        ///    |    /
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan5 {
            get {
                return ResourceManager.GetString("StickMan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    +-----+
        ///    |     |
        ///    |     0
        ///    |    /|\
        ///    |     |
        ///    |    / \
        ///    |
        ///   ++-------+
        ///   |        |
        ///   +--------+
        ///.
        /// </summary>
        internal static string StickMan6 {
            get {
                return ResourceManager.GetString("StickMan6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Hangman!
        ///.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the word?.
        /// </summary>
        internal static string WhatWasWord {
            get {
                return ResourceManager.GetString("WhatWasWord", resourceCulture);
            }
        }
    }
}
